# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidoPaterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellidoMaterno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('carrera', models.IntegerField(verbose_name='Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
