# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_auto_20170405_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.Carrera'),
        ),
    ]
