# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_auto_20170405_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.IntegerField(default=0),
        ),
    ]
